#!/bin/bash

# Function to prompt for installation
install_prompt() {
    local app_name=$1
    local script=$2
    read -p "Do you want to install $app_name? ([y]/n): " response
    response=$(echo "$response" | tr '[:upper:]' '[:lower:]')
    # response=${response,,}  # Convert response to lowercase
    if [[ -z $response ]]; then
        response="yes" # If the response is empty, set it to "yes"
    fi
    if [[ $response == "yes" || $response == "y" ]]; then
        $script
    fi
}

# Call the function for each app
install_prompt "tmux" "./scripts/install_tmux.sh"
install_prompt "Neovim" "./scripts/install_nvim.sh"
install_prompt "oh-my-posh" "./scripts/install_ohmyposh.sh"
install_prompt "fzf" "./scripts/install_fzf.sh"
install_prompt "fastfetch" "./scripts/install_fastfetch.sh"
install_prompt "yazi" "./scripts/install_yazi.sh"
install_prompt "zoxide" "./scripts/install_zoxide.sh"
# TODO: Add lazygit
